"""add_user_settings_fields

Revision ID: a67d7e971965
Revises: 6fcb2ab12530
Create Date: 2025-11-09 02:00:34.546617

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a67d7e971965'
down_revision = '6fcb2ab12530'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('risks', 'probability',
               existing_type=postgresql.ENUM('low', 'medium', 'high', name='riskprobability'),
               nullable=True,
               existing_server_default=sa.text("'medium'::riskprobability"))
    op.alter_column('risks', 'impact',
               existing_type=postgresql.ENUM('low', 'medium', 'high', 'critical', name='riskimpact'),
               nullable=True,
               existing_server_default=sa.text("'medium'::riskimpact"))
    op.add_column('users', sa.Column('profile_picture', sa.String(), nullable=True))
    op.add_column('users', sa.Column('notification_preferences', sa.JSON(), nullable=True))
    op.add_column('users', sa.Column('user_preferences', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'user_preferences')
    op.drop_column('users', 'notification_preferences')
    op.drop_column('users', 'profile_picture')
    op.alter_column('risks', 'impact',
               existing_type=postgresql.ENUM('low', 'medium', 'high', 'critical', name='riskimpact'),
               nullable=False,
               existing_server_default=sa.text("'medium'::riskimpact"))
    op.alter_column('risks', 'probability',
               existing_type=postgresql.ENUM('low', 'medium', 'high', name='riskprobability'),
               nullable=False,
               existing_server_default=sa.text("'medium'::riskprobability"))
    # ### end Alembic commands ###
