"use client";

import { useState } from "react";
import { Button } from "@/components/ui/button";
import { Textarea } from "@/components/ui/textarea";
import { Select } from "@/components/ui/select";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Bot, Wand2, Copy, Download, RotateCcw } from "lucide-react";

const AI_MODELS = [
  { value: "gpt-4", label: "GPT-4" },
  { value: "gpt-3.5-turbo", label: "GPT-3.5 Turbo" },
  { value: "claude-3", label: "Claude 3" },
  { value: "gemini-pro", label: "Gemini Pro" },
];

const PROMPT_TEMPLATES = [
  {
    name: "Project Summary",
    prompt:
      "Create a comprehensive project summary including objectives, timeline, key deliverables, and potential risks for:",
  },
  {
    name: "Risk Assessment",
    prompt:
      "Analyze potential risks and provide mitigation strategies for the following project scenario:",
  },
  {
    name: "Task Breakdown",
    prompt:
      "Break down the following project into specific, actionable tasks with estimated timeframes:",
  },
  {
    name: "Meeting Agenda",
    prompt: "Create a detailed meeting agenda for discussing:",
  },
];

interface GeneratedResult {
  id: string;
  content: string;
  timestamp: Date;
}

export default function AIStudioPage() {
  const [prompt, setPrompt] = useState("");
  const [selectedModel, setSelectedModel] = useState("gpt-4");
  const [outputCount, setOutputCount] = useState(1);
  const [isGenerating, setIsGenerating] = useState(false);
  const [results, setResults] = useState<GeneratedResult[]>([]);

  const handleTemplateSelect = (template: typeof PROMPT_TEMPLATES[0]) => {
    setPrompt(template.prompt);
  };

  const handleGenerate = async () => {
    if (!prompt.trim()) return;

    setIsGenerating(true);

    // Simulate AI generation with mock responses
    setTimeout(() => {
      const newResults: GeneratedResult[] = [];

      for (let i = 0; i < outputCount; i++) {
        newResults.push({
          id: `${Date.now()}-${i}`,
          content: `Generated response ${i + 1}:\n\nThis is a mock AI-generated response for the prompt: "${prompt.substring(0, 50)}..."\n\nKey Points:\n• Analysis of the requirements\n• Strategic recommendations\n• Implementation timeline\n• Risk mitigation strategies\n• Success metrics and KPIs\n\nThis is placeholder content that would normally be generated by the selected AI model (${selectedModel}).`,
          timestamp: new Date(),
        });
      }

      setResults(newResults);
      setIsGenerating(false);
    }, 2000 + Math.random() * 1000);
  };

  const handleCopy = (content: string) => {
    navigator.clipboard.writeText(content);
    // TODO: Add toast notification
  };

  const handleExport = () => {
    const exportData = {
      prompt,
      model: selectedModel,
      results,
      exportedAt: new Date().toISOString(),
    };

    const blob = new Blob([JSON.stringify(exportData, null, 2)], {
      type: "application/json",
    });

    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `ai-studio-export-${Date.now()}.json`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  const handleClear = () => {
    setPrompt("");
    setResults([]);
  };

  return (
    <div className="space-y-6">
      <div>
        <h1 className="text-3xl font-bold flex items-center gap-2">
          <Bot className="h-8 w-8" />
          AI Studio
        </h1>
        <p className="text-muted-foreground">
          Generate content, analyze data, and get AI-powered insights for your projects.
        </p>
      </div>

      <div className="grid gap-6 lg:grid-cols-3">
        <div className="lg:col-span-2 space-y-4">
          <Card>
            <CardHeader>
              <CardTitle>AI Configuration</CardTitle>
            </CardHeader>
            <CardContent className="space-y-4">
              <div className="grid grid-cols-2 gap-4">
                <div className="space-y-2">
                  <Label htmlFor="model">AI Model</Label>
                  <Select
                    value={selectedModel}
                    onChange={(e) => setSelectedModel(e.target.value)}
                  >
                    {AI_MODELS.map((model) => (
                      <option key={model.value} value={model.value}>
                        {model.label}
                      </option>
                    ))}
                  </Select>
                </div>
                <div className="space-y-2">
                  <Label htmlFor="outputs">Number of Outputs</Label>
                  <Input
                    id="outputs"
                    type="number"
                    min="1"
                    max="5"
                    value={outputCount}
                    onChange={(e) => setOutputCount(parseInt(e.target.value) || 1)}
                  />
                </div>
              </div>

              <div className="space-y-2">
                <Label>Quick Templates</Label>
                <div className="flex flex-wrap gap-2">
                  {PROMPT_TEMPLATES.map((template) => (
                    <Button
                      key={template.name}
                      variant="outline"
                      size="sm"
                      onClick={() => handleTemplateSelect(template)}
                    >
                      {template.name}
                    </Button>
                  ))}
                </div>
              </div>

              <div className="space-y-2">
                <Label htmlFor="prompt">Prompt</Label>
                <Textarea
                  id="prompt"
                  placeholder="Enter your prompt here... Be specific about what you want the AI to generate."
                  value={prompt}
                  onChange={(e) => setPrompt(e.target.value)}
                  rows={8}
                />
              </div>

              <div className="flex gap-2">
                <Button
                  onClick={handleGenerate}
                  disabled={!prompt.trim() || isGenerating}
                  className="flex-1"
                >
                  {isGenerating ? (
                    <>
                      <div className="animate-spin rounded-full h-4 w-4 border-2 border-current border-t-transparent mr-2" />
                      Generating...
                    </>
                  ) : (
                    <>
                      <Wand2 className="h-4 w-4 mr-2" />
                      Generate
                    </>
                  )}
                </Button>
                <Button variant="outline" onClick={handleClear}>
                  <RotateCcw className="h-4 w-4 mr-2" />
                  Clear
                </Button>
              </div>
            </CardContent>
          </Card>
        </div>

        <div className="space-y-4">
          <Card>
            <CardHeader>
              <CardTitle>Generation History</CardTitle>
            </CardHeader>
            <CardContent>
              <div className="space-y-2 text-sm">
                <div className="flex justify-between">
                  <span>Total Generations:</span>
                  <span className="font-medium">12</span>
                </div>
                <div className="flex justify-between">
                  <span>This Session:</span>
                  <span className="font-medium">{results.length}</span>
                </div>
                <div className="flex justify-between">
                  <span>Current Model:</span>
                  <span className="font-medium">
                    {AI_MODELS.find(m => m.value === selectedModel)?.label}
                  </span>
                </div>
              </div>
            </CardContent>
          </Card>
        </div>
      </div>

      {results.length > 0 && (
        <Card>
          <CardHeader className="flex flex-row items-center justify-between">
            <CardTitle>Generated Results</CardTitle>
            <Button variant="outline" size="sm" onClick={handleExport}>
              <Download className="h-4 w-4 mr-2" />
              Export
            </Button>
          </CardHeader>
          <CardContent className="space-y-6">
            {results.map((result, index) => (
              <div
                key={result.id}
                className="border rounded-lg p-4 space-y-3 bg-muted/30"
              >
                <div className="flex items-center justify-between">
                  <h4 className="font-medium">Output {index + 1}</h4>
                  <div className="flex items-center gap-2">
                    <span className="text-xs text-muted-foreground">
                      {result.timestamp.toLocaleTimeString()}
                    </span>
                    <Button
                      variant="ghost"
                      size="sm"
                      onClick={() => handleCopy(result.content)}
                    >
                      <Copy className="h-4 w-4" />
                    </Button>
                  </div>
                </div>
                <div className="whitespace-pre-wrap text-sm bg-background p-3 rounded border">
                  {result.content}
                </div>
              </div>
            ))}
          </CardContent>
        </Card>
      )}
    </div>
  );
}